# Generated by Django 5.0.6 on 2024-06-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('degree', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='person',
            old_name='firstName',
            new_name='firstname',
        ),
    ]
