# Generated by Django 5.0.6 on 2024-06-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_doctor_rename_firstname_person_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('doctorname', models.CharField(max_length=50)),
                ('timing', models.TimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
