# Generated by Django 5.0.6 on 2024-06-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctorname',
            new_name='doctor',
        ),
    ]
