# Generated by Django 5.0.6 on 2024-06-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
