# Generated by Django 5.0.6 on 2024-06-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_doctor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='doctorname',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timing',
            field=models.CharField(max_length=30),
        ),
    ]
