# Generated by Django 5.0.6 on 2024-06-23 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_doctorname_appointment_doctor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('page', models.IntegerField()),
                ('pemail', models.EmailField(max_length=50)),
                ('pphone', models.CharField(max_length=20)),
                ('pgender', models.CharField(max_length=20)),
                ('pdiagnosis', models.TextField()),
                ('pprescription', models.TextField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
